# Generated by Django 6.0 on 2026-01-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='health_issues',
            field=models.TextField(blank=True, help_text='Any medical conditions or injuries', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
