# Generated by Django 6.0 on 2026-01-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_weightlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_weight',
            field=models.FloatField(blank=True, help_text='Target Weight in kg', null=True),
        ),
    ]
