# Generated by Django 6.0 on 2026-01-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_target_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_steps',
            field=models.IntegerField(blank=True, help_text='Target Steps', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_water',
            field=models.FloatField(blank=True, help_text='Target Water in Liters', null=True),
        ),
        migrations.AddField(
            model_name='weightlog',
            name='steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weightlog',
            name='water',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
