# Generated by Django 6.0 on 2026-01-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_target_steps_userprofile_target_water_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightlog',
            name='steps',
            field=models.IntegerField(default=0, help_text='Steps count'),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='water',
            field=models.FloatField(default=0, help_text='Water in Liters'),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
