# Generated by Django 6.0 on 2026-01-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_weightlog_steps_alter_weightlog_water_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('youtube_id', models.CharField(max_length=50)),
                ('plan_type', models.CharField(choices=[('All', 'All Plans'), ('Power Packer 90', 'Power Packer 90'), ('Gold', 'Gold'), ('elite', 'Elite')], default='All', max_length=50)),
                ('unlock_day', models.IntegerField(default=0, help_text='Day number from start_date when this unlocks')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['unlock_day', 'order'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='blueprint_start_date',
            field=models.DateField(blank=True, help_text='The date the user actually starts the plan', null=True),
        ),
    ]
