# Generated by Django 6.0 on 2026-01-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_academyvideo_subscription_blueprint_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademyVideo',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='blueprint_start_date',
        ),
    ]
