# Generated by Django 6.0 on 2026-01-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_academyvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='blueprint_start_date',
            field=models.DateField(blank=True, help_text='The date the user actually starts the plan', null=True),
        ),
    ]
