# Generated by Django 6.0 on 2026-01-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_subscription_blueprint_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='initial_weight',
            field=models.FloatField(blank=True, help_text='Starting weight in kg', null=True),
        ),
    ]
