# Generated by Django 6.0 on 2026-01-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_userprofile_age_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_email_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
