# Generated by Django 6.0 on 2026-01-26 11:30

from django.db import migrations


def create_superuser(apps, schema_editor):
    from django.contrib.auth.models import User
    if not User.objects.filter(username='superadmin').exists():
        User.objects.create_superuser(
            username='superadmin',
            email='admin@bunnysblueprint.com',
            password='AdminPassword123!'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userprofile_daily_email_reminders'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
