# Generated by Django 6.0 on 2026-01-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20260126_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_email_reminders',
            field=models.BooleanField(default=False),
        ),
    ]
